# This file was generated by GoReleaser. DO NOT EDIT.
cask "stitch" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "dd8f8725357a3e00f16b086e5e1dda7284e037368fe492cc233836c161763bb6"
      url "https://github.com/onancelabs/stitch/releases/download/v#{version}/stitch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc10a1884c465936ecddcc553d050f523c26230ea74513668d5f4ef926424191"
      url "https://github.com/onancelabs/stitch/releases/download/v#{version}/stitch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "54c5a2a1b26ab7d33e8972973866fd84aca3ffc4ead74c6103a0347c1881e97f"
      url "https://github.com/onancelabs/stitch/releases/download/v#{version}/stitch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "502897b1c301d08a8ccdb471b885be99d4dd011c7381c9aa16148e5534009f42"
      url "https://github.com/onancelabs/stitch/releases/download/v#{version}/stitch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stitch"
  desc "Stacked branches and stacked pull requests on top of plain git"
  homepage "https://github.com/onancelabs/stitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "st"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/st"]
    end
  end

  # No zap stanza required

end
