# This file was generated by GoReleaser. DO NOT EDIT.
cask "stitch" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "69e6fc6afb4ecbb08a3a7d926736b9e955df06a654468fdd236479748eba7857"
      url "https://github.com/onancelabs/stitch/releases/download/v#{version}/stitch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b556dcbd52d75676597c272800f9d6d62c2f3b8dcc0f08ee3a5021fa1f2e70ad"
      url "https://github.com/onancelabs/stitch/releases/download/v#{version}/stitch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f3730a884684f92826cdab57fa18b93a2148ed1ee4d458a81bfa65b5de6f5937"
      url "https://github.com/onancelabs/stitch/releases/download/v#{version}/stitch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6eb98f94a302cf76dfdef533591b8d9f5bf431a0664d0309d2fa5437106f667d"
      url "https://github.com/onancelabs/stitch/releases/download/v#{version}/stitch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stitch"
  desc "Stacked branches and stacked pull requests on top of plain git"
  homepage "https://github.com/onancelabs/stitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stitch"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/st"]
    end
  end

  # No zap stanza required

end
